spring.application.name=event-ticketing-backend
# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/event_ticketing
spring.datasource.username=postgres
spring.datasource.password=vaibhav123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger UI Path (Springdoc OpenAPI)
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
